name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  build-oeq:
    name: Build oeq dist 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: install dependencies, then build source tarball
      run: |
        cd openequivariance 
        python3 -m pip install build 
        python3 -m build --sdist
    - name: store the distribution packages 
      uses: actions/upload-artifact@v4
      with:
        name: oeq-package-distributions
        path: openequivariance/dist/

  pypi-publish:
    name: Upload oeq to PyPI
    runs-on: ubuntu-latest
    needs: build-oeq
    environment: 
        name: pypi
        url: https://pypi.org/p/openequivariance
    permissions:
      id-token: write
    steps:
      - name: download the distributions
        uses: actions/download-artifact@v4
        with:
          name: oeq-package-distributions
          path: dist/ 
      - name: publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  # ------------------------------------

  build-oeq-extjax:
    name: Build extjax dist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: install dependencies, then build source tarball
      run: |
        cd openequivariance_extjax 
        python3 -m pip install build 
        python3 -m build --sdist 
    - name: store the distribution packages 
      uses: actions/upload-artifact@v4
      with:
        name: oeqjax-package-distributions
        path: openequivariance_extjax/dist/

  pypi-publish-extjax:
    name: Upload extjax to PyPI
    runs-on: ubuntu-latest
    needs: build-oeq-extjax
    environment: 
        name: pypi
        url: https://pypi.org/p/openequivariance_extjax
    permissions:
      id-token: write
    steps:
      - name: download the distributions
        uses: actions/download-artifact@v4
        with:
          name: oeqjax-package-distributions
          path: dist/ 
      - name: publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
